spring:
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST}
      port: ${SPRING_CLOUD_CONSUL_PORT}
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info