server:
  port: 8082

spring:
  datasource:
    url: ${DB_URL}
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

 # data:
  #  mongodb:
   #   uri: ${MONGODB_URI}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true