server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL}
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

RIOT_API_KEY: ${RIOT_API_KEY}